export default [
	// clubs
	{ id: 1, value:1,  color: 'black', flipped: true, face: 'ace', suit: 'clubs', position: [0, 0]},
	{ id: 2, value:2,  color: 'black', flipped: true, face: '2', suit: 'clubs', position: [-100, 0]},
	{ id: 3, value:3,  color: 'black', flipped: true, face: '3', suit: 'clubs', position: [-200, 0]},
	{ id: 4, value:4,  color: 'black', flipped: true, face: '4', suit: 'clubs', position: [-300, 0]},
	{ id: 5, value:5,  color: 'black', flipped: true, face: '5', suit: 'clubs', position: [-400, 0]},
	{ id: 6, value:6,  color: 'black', flipped: true, face: '6', suit: 'clubs', position: [-500, 0]},
	{ id: 7, value:7,  color: 'black', flipped: true, face: '7', suit: 'clubs', position: [-600, 0]},
	{ id: 8, value:8,  color: 'black', flipped: true, face: '8', suit: 'clubs', position: [-700, 0]},
	{ id: 9, value:9,  color: 'black', flipped: true, face: '9', suit: 'clubs', position: [-800, 0]},
	{ id: 10, value: 10, color: 'black', flipped: true, face: '10', suit: 'clubs', position: [-900, 0]},
	{ id: 11, value: 11, color: 'black', flipped: true, face: 'Jack', suit: 'clubs', position: [-1000, 0]},
	{ id: 12, value: 12, color: 'black', flipped: true, face: 'Queen', suit: 'clubs', position: [-1100, 0]},
	{ id: 13, value: 13, color: 'black', flipped: true, face: 'King', suit: 'clubs', position: [-1200, 0]},

	// hearts
	{ id: 14, value:1, color: 'red', flipped: true, face: 'ace', suit: 'hearts', position: [0, -140]},
	{ id: 15, value:2, color: 'red', flipped: true, face: '2', suit: 'hearts', position: [-100, -140]},
	{ id: 16, value:3, color: 'red', flipped: true, face: '3', suit: 'hearts', position: [-200, -140]},
	{ id: 17, value:4, color: 'red', flipped: true, face: '4', suit: 'hearts', position: [-300, -140]},
	{ id: 18, value:5, color: 'red', flipped: true, face: '5', suit: 'hearts', position: [-400, -140]},
	{ id: 19, value:6, color: 'red', flipped: true, face: '6', suit: 'hearts', position: [-500, -140]},
	{ id: 20, value:7, color: 'red', flipped: true, face: '7', suit: 'hearts', position: [-600, -140]},
	{ id: 21, value:8, color: 'red', flipped: true, face: '8', suit: 'hearts', position: [-700, -140]},
	{ id: 22, value:9, color: 'red', flipped: true, face: '9', suit: 'hearts', position: [-800, -140]},
	{ id: 23, value: 10, color: 'red', flipped: true, face: '10', suit: 'hearts', position: [-900, -140]},
	{ id: 24, value: 11, color: 'red', flipped: true, face: 'Jack', suit: 'hearts', position: [-1000, -140]},
	{ id: 25, value: 12, color: 'red', flipped: true, face: 'Queen', suit: 'hearts', position: [-1100, -140]},
	{ id: 26, value: 13, color: 'red', flipped: true, face: 'King', suit: 'hearts', position: [-1200, -140]},

	// spades
	{ id: 27, value:1, color: 'black', flipped: true, face: 'ace', suit: 'spades', position: [0, -280]},
	{ id: 28, value:2, color: 'black', flipped: true, face: '2', suit: 'spades', position: [-100, -280]},
	{ id: 29, value:3, color: 'black', flipped: true, face: '3', suit: 'spades', position: [-200, -280]},
	{ id: 30, value:4, color: 'black', flipped: true, face: '4', suit: 'spades', position: [-300, -280]},
	{ id: 31, value:5, color: 'black', flipped: true, face: '5', suit: 'spades', position: [-400, -280]},
	{ id: 32, value:6, color: 'black', flipped: true, face: '6', suit: 'spades', position: [-500, -280]},
	{ id: 33, value:7, color: 'black', flipped: true, face: '7', suit: 'spades', position: [-600, -280]},
	{ id: 34, value:8, color: 'black', flipped: true, face: '8', suit: 'spades', position: [-700, -280]},
	{ id: 35, value:9, color: 'black', flipped: true, face: '9', suit: 'spades', position: [-800, -280]},
	{ id: 36, value: 10, color: 'black', flipped: true, face: '10', suit: 'spades', position: [-900, -280]},
	{ id: 37, value: 11, color: 'black', flipped: true, face: 'Jack', suit: 'spades', position: [-1000, -280]},
	{ id: 38, value: 12, color: 'black', flipped: true, face: 'Queen', suit: 'spades', position: [-1100, -280]},
	{ id: 39, value: 13, color: 'black', flipped: true, face: 'King', suit: 'spades', position: [-1200, -280]},

			// diamonds
	{ id: 40, value:1, color: 'red', flipped: true, face: 'ace', suit: 'diamonds', position: [0, -420]},
	{ id: 41, value:2, color: 'red', flipped: true, face: '2', suit: 'diamonds', position: [-100, -420]},
	{ id: 42, value:3, color: 'red', flipped: true, face: '3', suit: 'diamonds', position: [-200, -420]},
	{ id: 43, value:4, color: 'red', flipped: true, face: '4', suit: 'diamonds', position: [-300, -420]},
	{ id: 44, value:5, color: 'red', flipped: true, face: '5', suit: 'diamonds', position: [-400, -420]},
	{ id: 45, value:6, color: 'red', flipped: true, face: '6', suit: 'diamonds', position: [-500, -420]},
	{ id: 46, value:7, color: 'red', flipped: true, face: '7', suit: 'diamonds', position: [-600, -420]},
	{ id: 47, value:8, color: 'red', flipped: true, face: '8', suit: 'diamonds', position: [-700, -420]},
	{ id: 48, value:9, color: 'red', flipped: true, face: '9', suit: 'diamonds', position: [-800, -420]},
	{ id: 49, value: 10, color: 'red', flipped: true, face: '10', suit: 'diamonds', position: [-900, -420]},
	{ id: 50, value: 11, color: 'red', flipped: true, face: 'Jack', suit: 'diamonds', position: [-1000, -420]},
	{ id: 51, value: 12, color: 'red', flipped: true, face: 'Queen', suit: 'diamonds', position: [-1100, -420]},
	{ id: 52, value: 13, color: 'red', flipped: true, face: 'King', suit: 'diamonds', position: [-1200, -420]}
];
